[package]
name = "ferrite"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
miette = { version = "7.0", features = ["fancy"] }
thiserror = "1.0"
clap = { version = "4.5", features = ["derive"] }

[[bin]]
name = "ferrite"
path = "src/main.rs"
